version: '3.9'
services:
  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - my-network
    deploy:
      replicas: 2
      placement:
        preferences:
          - spread: node.hostname


  backend:
    image: gabreudev/backendspring:latest
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    networks:
      - my-network
    deploy:
      replicas: 2
      placement:
        preferences:
          - spread: node.hostname
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
        window: 30s

networks:
  my-network:
    driver: overlay
