version: '3.1'
services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"

  init:
    image: cassandra:latest
    depends_on:
      - cassandra
    entrypoint: ["/bin/bash", "/init.sh"]
    volumes:
      - ./init.sh:/init.sh
